version: '3'
services:
  nuxtapp:
    build: .
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: production
      NITRO_PRESET: digital-ocean
    volumes:
      - .:/app
      - /app/node_modules
